const KEY="zc-education-desk-vault-v1",STATE="zc-education-desk-state-v1";let vault=null,visible=50;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function load(){try{const raw=localStorage.getItem(KEY);if(raw){vault=JSON.parse(raw);start()}}catch{localStorage.removeItem(KEY)}}
function state(){try{return JSON.parse(localStorage.getItem(STATE))||{}}catch{return{}}}function saveState(p){localStorage.setItem(STATE,JSON.stringify({...state(),...p}))}
function start(){if(!vault?.readingLibrary||!vault?.knowledgeData)return;$("#gate").hidden=true;$("#app").hidden=false;const s=state();$("#focus").value=s.focus||vault.profile?.defaultFocus||"";$("#next").value=s.next||"";const readings=vault.readingLibrary.modules.flatMap(m=>m.readings);$("#record-count").textContent=readings.length.toLocaleString();$("#concept-count").textContent=vault.knowledgeData.concepts.length;$("#thinker-count").textContent=vault.knowledgeData.thinkers.length;renderReadings();renderConcepts();renderThinkers()}
$("#import-file").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(data.format!=="education-desk-vault"||!data.readingLibrary||!data.knowledgeData)throw Error();localStorage.setItem(KEY,JSON.stringify(data));if(data.personalState)localStorage.setItem(STATE,JSON.stringify(data.personalState));vault=data;start();toast("Workspace imported") }catch{alert("This is not a valid Education Desk backup.")}e.target.value=""});
$("#focus").addEventListener("input",e=>saveState({focus:e.target.value}));$("#next").addEventListener("input",e=>saveState({next:e.target.value}));
$$('[data-view]').forEach(b=>b.addEventListener("click",()=>{$$('[data-view]').forEach(x=>x.classList.remove("active"));$$('.view').forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.view).classList.add("active");scrollTo(0,0)}));
$("#lock").addEventListener("click",()=>{if(confirm("Remove the private workspace from this browser? Export a backup first if needed.")){localStorage.removeItem(KEY);localStorage.removeItem(STATE);location.reload()}});
$("#export").addEventListener("click",()=>{const out={...vault,personalState:state(),exportedAt:new Date().toISOString()};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:"application/json"}));a.download=`education-desk-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)});
function allReadings(){return vault.readingLibrary.modules.flatMap(m=>m.readings)}function readingStatus(id){return state().readings?.[id]||"unread"}function setReading(id,v){const s=state();saveState({readings:{...(s.readings||{}),[id]:v}})}
function renderReadings(){const q=$("#search").value.toLowerCase();const rows=allReadings().filter(r=>[r.title,r.authors,r.module,r.container,r.section].join(" ").toLowerCase().includes(q));$("#results-meta").textContent=`${rows.length.toLocaleString()} records · showing ${Math.min(rows.length,visible)}`;$("#readings").replaceChildren(...rows.slice(0,visible).map(r=>{const a=document.createElement("article");a.className="reading";const d=document.createElement("div"),h=document.createElement("h3"),p=document.createElement("p"),s=document.createElement("select");h.textContent=r.title;p.textContent=[r.authors,r.year,r.module,r.section].filter(Boolean).join(" · ");[["unread","Unread"],["queue","Queue"],["reading","Reading"],["read","Read"],["critical","Critical"]].forEach(([v,t])=>{const o=document.createElement("option");o.value=v;o.textContent=t;s.append(o)});s.value=readingStatus(r.id);s.addEventListener("change",()=>setReading(r.id,s.value));d.append(h,p);a.append(d,s);return a}));$("#more").hidden=visible>=rows.length}
$("#search").addEventListener("input",()=>{visible=50;renderReadings()});$("#more").addEventListener("click",()=>{visible+=50;renderReadings()});
function renderConcepts(){const q=$("#concept-search").value.toLowerCase();const rows=vault.knowledgeData.concepts.filter(c=>Object.values(c).join(" ").toLowerCase().includes(q));$("#concept-list").replaceChildren(...rows.map(c=>{const a=document.createElement("article");a.className="concept";const sm=document.createElement("small"),h=document.createElement("h3"),z=document.createElement("p"),d=document.createElement("p"),b=document.createElement("blockquote");sm.textContent=c.domain;h.textContent=c.name;z.className="zh";z.textContent=c.zh;d.textContent=c.definition;b.textContent=c.question;a.append(sm,h,z,d,b);return a}))}$("#concept-search").addEventListener("input",renderConcepts);
function renderThinkers(){const q=$("#thinker-search").value.toLowerCase();const rows=vault.knowledgeData.thinkers.filter(t=>Object.values(t).join(" ").toLowerCase().includes(q));$("#thinker-list").replaceChildren(...rows.map(t=>{const a=document.createElement("article");a.className="thinker";const d=document.createElement("div"),h=document.createElement("h3"),p=document.createElement("p");h.textContent=t.name;p.textContent=`${t.ideas} · Start with: ${t.works} · Critique: ${t.critique}`;d.append(h,p);a.append(d);return a}))}$("#thinker-search").addEventListener("input",renderThinkers);load();
